disable-message: "&8[&bMineverse&8] &8Fly has been &cDISABLED"
enable-message: "&8[&bMineverse&8] &8Fly has been &aENABLED"
no-perm-fly: "&8[&bMineverse&8] &cYou need permission mvcore.fly to execute this command"
join-message-prefix: '&8[&a+&8] &r'
join-message: ' &bhas joined the server'
leave-message-prefix: '&8[&c-&8] &r'
leave-message: ' &bhas left the server'
spawn-location: